apiVersion: v2
name: oblien-domains
description: A Helm chart for Oblien Domains - Open Source Domain Register & Manager
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - domain
  - dns
  - registration
  - management
  - opensrs
maintainers:
  - name: Oblien Team
    email: support@oblien.com
    url: https://github.com/oblien/oblien-domains
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "22.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled 